/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IframeRouteImport } from './routes/iframe'
import { Route as IndexRouteImport } from './routes/index'

const IframeRoute = IframeRouteImport.update({
  id: '/iframe',
  path: '/iframe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/iframe': typeof IframeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/iframe': typeof IframeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/iframe': typeof IframeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/iframe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/iframe'
  id: '__root__' | '/' | '/iframe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IframeRoute: typeof IframeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iframe': {
      id: '/iframe'
      path: '/iframe'
      fullPath: '/iframe'
      preLoaderRoute: typeof IframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IframeRoute: IframeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
